---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribbble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: Crowdsourced, for Fontello project
  homepage: http://fontello.com
  email: vitaly@rcdesign.ru
  twitter: http://twitter.com/puzrin
  github: https://github.com/fontello/fontelico
  license: SIL
  license_url: http://scripts.sil.org/OFL

  css_prefix: "icon-"
  columns: 4

#transform:
#  baseline: 0.4
#  rescale: 2.4

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: fontelico

  fullname: Fontelico
  familyname: Fontelico

  copyright: Copyright (C) 2012 by Fontello project

  ascent: 850
  descent: 150
  weight: Normal


glyphs:

  -
    css: emo-happy
    code: 0xe800
    uid: c64623255a4a7c72436b199b05296c4f
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, happy]
  -
    css: emo-wink
    code: 0xe801
    uid: 1ba44825e5f10920b4e3f1d0c73f79a2
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, wink]
  -
    css: emo-wink2
    code: 0xe813
    uid: 4bb2045a2aca451705fe8a23c4a576ab
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, wink]
  -
    css: emo-unhappy
    code: 0xe802
    uid: 53ed8570225581269cd7eff5795e8bea
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, unhappy]
  -
    css: emo-sleep
    code: 0xe803
    uid: fd59eac4d575b48eb156590b63a355fd
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, sleep]
  -
    css: emo-thumbsup
    code: 0xe804
    uid: 142263941b9f4cd4b2b84f1f4cd13b1d
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, thumbsup]
  -
    css: emo-devil
    code: 0xe805
    uid: 4dd56d61fd0dab19277824da301424b3
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, devil]
  -
    css: emo-surprised
    code: 0xe806
    uid: 68e298ff2d8b25dd7f647ed64f5ae690
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, surprised]
  -
    css: emo-tongue
    code: 0xe807
    uid: bb68a13a3574b087d4350eff0b8d48e3
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, tongue]
  -
    css: emo-coffee
    code: 0xe808
    uid: 48cc210e59ff4bc56b6c8fba6eb384b8
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, coffee]
  -
    css: emo-sunglasses
    code: 0xe809
    uid: 078fec38562c3f83a1201a908040c141
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, sunglasses]
  -
    css: emo-displeased
    code: 0xe80a
    uid: 043b585886018be7408f4c77c1a3759c
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, displeased]
  -
    css: emo-beer
    code: 0xe80b
    uid: 043b585886018be7408f4c77c1a3759c
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, beer]
  -
    css: emo-grin
    code: 0xe80c
    uid: cbc328d1c779a2b9e3b1199d904199a5
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, grin]
  -
    css: emo-angry
    code: 0xe80d
    uid: f0d3ad15d020cf187d42dd3b2295b65c
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, angry]
  -
    css: emo-saint
    code: 0xe80e
    uid: 5195e2dcb4a63fbb8c09896a8058f6ab
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, saint]
  -
    css: emo-cry
    code: 0xe80f
    uid: 04688d76a33ce7a7950e40fae79c08ac
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, cry]
  -
    css: emo-shoot
    code: 0xe810
    uid: 4843d0d6050dd508d4c101a334f46db2
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, shoot]
  -
    css: emo-squint
    code: 0xe811
    uid: fc92480dedc439d274d4e3e4b425edf4
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, squint]
  -
    css: emo-laugh
    code: 0xe812
    uid: 2bd5f98482d86649958312ea2ab5bb40
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [emoticon, smiley, laugh]

  -
    css: spin1
    code: 0xe830
    uid: 72109d2fb3088d0e66ea6a9204297651
    css-ext: animate-spin
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [load, progress, wait]
  -
    css: spin2
    code: 0xe831
    uid: f0c301ac841dafc38d8eb1b933fc73e5
    css-ext: animate-spin
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [load, progress, wait]
  -
    css: spin3
    code: 0xe832
    uid: 2a6740fc2f9d0edea54205963f662594
    css-ext: animate-spin
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [load, progress, wait]
  -
    css: spin4
    code: 0xe834
    uid: 9bd60140934a1eb9236fd7a8ab1ff6ba
    css-ext: animate-spin
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [load, progress, wait]
  -
    css: spin5
    code: 0xe838
    uid: 5d2d07f112b8de19f2c0dbfec3e42c05
    css-ext: animate-spin
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [load, progress, wait]
  -
    css: spin6
    code: 0xe839
    uid: 9bc2902722abb366a213a052ade360bc
    css-ext: animate-spin
    meta:
      author: Angela Berbentseva, specially for fontello
      email: berbentseva_angela@yahoo.com
    search: [load, progress, wait]

